import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
await mkdir('tests/screenshots',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1480,height:920},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:18766');
await page.getByRole('heading',{name:'题目总表',exact:true}).waitFor();
await page.locator('.problem-table tbody tr').first().waitFor();
await page.screenshot({path:'tests/screenshots/library-dark.png'});
await page.getByRole('button',{name:'题解分栏',exact:true}).click();
await page.locator('.markdown').waitFor();
await page.screenshot({path:'tests/screenshots/reader-dark.png'});
await page.getByRole('button',{name:'知识点地图',exact:true}).click();
await page.screenshot({path:'tests/screenshots/knowledge-dark.png'});
await page.locator('.sidebar .nav-item').filter({hasText:'偏好设置'}).click();
await page.screenshot({path:'tests/screenshots/settings-dark.png'});
await page.getByRole('button',{name:'切换明暗主题',exact:true}).click();
await page.getByRole('button',{name:'题目总表',exact:true}).click();
await page.screenshot({path:'tests/screenshots/library-light.png'});
await page.setViewportSize({width:2560,height:1400});
await page.screenshot({path:'tests/screenshots/library-wide.png'});
console.log(JSON.stringify({errors,title:await page.title(),rows:await page.locator('.problem-table tbody tr').count()}));
await browser.close();
