import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1480,height:920}});
const page=await context.newPage();
page.setDefaultTimeout(8000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const states=['未做','不会','待重写','复现AC','独立AC','巩固'];
const rows=states.map((status,i)=>({id:`周赛 164::${String.fromCharCode(65+i)}`,contest:'周赛 164',problem:String.fromCharCode(65+i),title:['前缀练习','树上查询','背包练习','区间统计','数论练习','字符串练习'][i],knowledge:['前缀和','LCA','背包 DP','前缀和 + 差分','素数','KMP'][i],tags:[['前缀和'],['LCA'],['背包 DP'],['前缀和','差分'],['素数'],['KMP']][i],difficulty:1300+i*100,status,date:i?'2026-09-01':'',platform:'牛客',series:'周赛',queue:[null,'fill','rewrite','review','review','check'][i]}));
rows.push({...rows[0],id:'ABC 478::F',contest:'ABC 478',problem:'F',title:'更多练习',tags:['前缀和','差分'],knowledge:'前缀和 + 差分',difficulty:2000,platform:'AtCoder'});
const categories=[{name:'前缀和与差分',tags:['前缀和','差分'],children:[{name:'前缀和',tags:['前缀和'],children:[]},{name:'差分',tags:['差分'],children:[]}]},{name:'图论',tags:['LCA'],children:[{name:'树',tags:['LCA'],children:[{name:'LCA',tags:['LCA'],children:[]}]}]}];
let revision=0,posts=0,skipConflict=false;
await context.route('**/api/**',async route=>{
 const req=route.request(),path=new URL(req.url()).pathname;
 let body;
 if(path==='/api/data')body={rows,statuses:states,categories,revision:String(revision),today:'2026-10-08',token:'fixture-token'};
 else if(path==='/api/inbox'&&req.method()==='GET')body={pending:1,conflicts:['练习冲突'],files:[]};
 else if(path==='/api/inbox'){const {action}=req.postDataJSON();body={pending:1,conflicts:['练习冲突'],needsChoice:action==='import',result:action!=='import'?{added:1}:undefined};skipConflict=action==='skip'}
 else if(path==='/api/solution')body={title:'fixture',path:'fixture.md',url:'https://example.com/problem',markdown:'## 题意\n\n这是公式 $x_{i} + y$。\n\n$$\\sum_{i=1}^{n} a_i$$\n\n## 参考代码\n\n```cpp\nint main() { return 0; }\n```'};
 else if(path==='/api/status'){const p=req.postDataJSON();assert.equal(req.headers()['x-tb-token'],'fixture-token');const r=rows.find(r=>r.id===p.id);if(r.status!==p.expected.status||r.date!==p.expected.date){await route.fulfill({status:409,json:{error:'状态已变化，请刷新'}});return}r.status=p.status;r.date=p.date??'2026-10-08';r.queue=p.status==='不会'?'fill':p.status==='待重写'?'rewrite':null;posts++;revision++;body={row:r,revision:String(revision)}}
 else throw Error('unexpected API '+path);
 await route.fulfill({json:body});
});
try{
 await page.goto('http://127.0.0.1:18766');
 await page.locator('.problem-table tbody tr').first().waitFor();
 assert.equal(await page.locator('.problem-table tbody tr').count(),7);
 await page.getByRole('textbox',{name:'搜索题目'}).fill('周赛 164 C');
 await page.waitForFunction(()=>document.querySelectorAll('.problem-table tbody tr').length===1);
 assert.match(await page.locator('.problem-table tbody').innerText(),/背包练习/);
 await page.getByRole('button',{name:'清空搜索'}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.problem-table tbody tr').length===7);
 await page.getByRole('button',{name:'收藏 前缀练习',exact:true}).click();
 await page.getByRole('button',{name:'收藏题目筛选'}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.problem-table tbody tr').length===1);
 await page.getByRole('button',{name:'收藏题目筛选'}).click();
 await page.getByRole('button',{name:'筛选',exact:true}).click();
 await page.getByRole('spinbutton',{name:'最低难度',exact:true}).fill('1500');
 await page.getByRole('spinbutton',{name:'最高难度',exact:true}).fill('1700');
 await page.waitForFunction(()=>document.querySelectorAll('.problem-table tbody tr').length===3);
 await page.getByRole('button',{name:'保存筛选',exact:true}).click();
 await page.getByRole('textbox',{name:'筛选名称'}).fill('训练范围');
 await page.getByRole('dialog',{name:'保存常用筛选'}).getByRole('button',{name:'保存筛选',exact:true}).click();
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.problem-table tbody tr').length===7);
 await page.getByRole('button',{name:'训练范围',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.problem-table tbody tr').length===3);
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();
 await page.getByRole('button',{name:'修改 周赛 164 A 状态',exact:true}).click();
 await page.getByRole('dialog',{name:'修改题目状态'}).getByRole('button').filter({hasText:'独立AC'}).click();
 await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('已保存'));
 assert.equal(rows[0].status,'独立AC');assert.equal(rows[0].date,'2026-10-08');
 await page.getByRole('button',{name:'撤销状态改动',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('已撤销'));
 assert.equal(rows[0].status,'未做');assert.equal(rows[0].date,'');
 await page.getByRole('button',{name:'恢复状态改动',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('已恢复'));
 assert.equal(rows[0].status,'独立AC');
 await page.getByRole('button',{name:'题解分栏',exact:true}).click();
 await page.locator('.markdown .katex').first().waitFor();
 assert.equal(await page.locator('.katex-error').count(),0);
 await page.getByRole('button',{name:'切换题解全屏'}).click();
 await page.locator('.full-reader').waitFor();
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('.full-reader').count(),0);
 await page.getByRole('button',{name:'收起题解',exact:true}).last().click();
 await page.getByRole('button',{name:'知识点地图',exact:true}).click();
 await page.getByRole('button',{name:'展开树',exact:true}).click();
 await page.getByRole('button',{name:'查看LCA题目',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.problem-table tbody tr').length===1);
 assert.match(await page.locator('.problem-table tbody').innerText(),/树上查询/);
 await page.getByRole('button',{name:'清除知识点筛选'}).click();
 await page.getByRole('button',{name:'训练推荐',exact:true}).click();
 await page.getByRole('dialog',{name:'安排一组训练'}).waitFor();
 await page.getByRole('button',{name:'开始第一题',exact:true}).click();
 assert.equal(await page.locator('.reader-panel').count(),0);
 assert.match(await page.locator('tr[data-selected=true]').innerText(),/背包练习/);
 await page.getByRole('button',{name:'收件箱',exact:true}).click();
 await page.getByRole('button',{name:'导入新题解',exact:true}).click();
 await page.getByRole('button',{name:'跳过冲突项',exact:true}).click();
 await page.getByRole('dialog',{name:'题解收件箱'}).waitFor({state:'detached'});
 assert.equal(skipConflict,true);
 await page.locator('.sidebar .nav-item').filter({hasText:'偏好设置'}).click();
 await page.getByRole('checkbox',{name:'界面动效'}).uncheck();
 await page.getByRole('button',{name:'澄空蓝',exact:true}).click();
 await page.getByRole('button',{name:'云白浅色',exact:true}).click();
 await page.reload();
 await page.locator('.problem-table tbody tr').first().waitFor();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 assert.equal(await page.locator('html').getAttribute('data-accent'),'blue');
 assert.equal(await page.locator('html').getAttribute('data-motion'),'off');
 await page.getByRole('button',{name:'收藏题目筛选'}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.problem-table tbody tr').length===1);
 await page.getByRole('button',{name:'收藏题目筛选'}).click();
 await page.locator('.table-scroll').focus();await page.keyboard.press('f');
 assert.equal(await page.getByRole('textbox',{name:'搜索题目'}).evaluate(el=>el===document.activeElement),true);
 await page.keyboard.type('tree');await page.keyboard.press('Escape');
 assert.equal(await page.getByRole('textbox',{name:'搜索题目'}).inputValue(),'');
 await page.keyboard.press('Enter');await page.keyboard.press('ArrowRight');
 await page.getByRole('heading',{name:'知识点地图',exact:true}).waitFor();
 await page.setViewportSize({width:1100,height:750});
 await page.getByRole('button',{name:'题目总表',exact:true}).click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);assert.equal(posts,3);
 await mkdir('tests/screenshots',{recursive:true});await page.screenshot({path:'tests/screenshots/fixture-responsive.png'});
 console.log('UI OK: search, filters, favorites, saved views, state + undo/redo, preview + math, category navigation, planner, inbox conflict, preferences, keyboard, responsive; 3 isolated writes, 0 page errors');
}finally{await browser.close()}
