import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import { chromium } from 'playwright';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const server = await createServer({ root, server: { host: '127.0.0.1', port: 18769, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1050, height: 760 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:18769/tests/v4-panels-fixture.html');
  await page.getByText('基础枚举', { exact: true }).waitFor();
  assert.equal(await page.locator('.progress-recommendation .competition-difficulty-intro').textContent(), '1100');
  assert.ok(await page.getByText('基础起步 · Round 2240', { exact: true }).isVisible());
  const heights = await page.evaluate(() => [...document.querySelectorAll('.progress-growth-columns > section')].map(node => node.getBoundingClientRect().height));
  assert.ok(Math.abs(heights[0] - heights[1]) > 20, 'cards keep natural heights');
  await page.locator('.progress-recommendation').getByRole('button', { name: '练习', exact: true }).focus();
  await page.keyboard.press('Enter');
  assert.deepEqual(await page.evaluate(() => window.panelsFixture.train), ['A']);
  await page.getByRole('button', { name: '赛事', exact: true }).click();
  await page.locator('.competition-card').first().waitFor();
  assert.deepEqual(await page.locator('.competition-card-title > strong').allTextContents(), ['Round 2250', 'Round 2240', 'Round 2257', 'Round 2256'], 'real dates first, unknown rounds newest first');
  assert.ok((await page.locator('.competition-card').nth(2).textContent()).includes('日期待同步'));
  for (const band of ['intro', 'basic', 'intermediate', 'challenge', 'advanced']) assert.ok(await page.locator(`.competition-difficulty-${band}`).count() > 0);
  await page.locator('.competition-card').first().focus();
  await page.keyboard.press('Enter');
  await page.getByRole('heading', { name: 'Round 2250', exact: true }).waitFor();
  assert.ok((await page.locator('.competition-detail-heading').textContent()).includes('2026/10/06'));
  await page.locator('.competition-question').first().getByRole('button', { name: '练习', exact: true }).click();
  assert.equal(await page.evaluate(() => window.panelsFixture.train.at(-1)), 'B');
  await page.getByRole('button', { name: '更新', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'GitHub公开仓库', exact: true }).count(), 0);
  assert.equal(await page.getByRole('link', { name: 'acm-agent-workflow', exact: true }).getAttribute('href'), 'https://github.com/3097729287/acm-agent-workflow');
  assert.ok(await page.getByText('项目公开仓库，当前公开包为旧图形端；React 发行待发布。', { exact: true }).isVisible());
  assert.equal(await page.getByRole('button', { name: '查看新增内容', exact: true }).count(), 1, 'remote-only notification cannot claim local targets');
  await page.getByRole('button', { name: '查看新增内容', exact: true }).focus();
  await page.keyboard.press('Enter');
  assert.deepEqual(await page.evaluate(() => window.panelsFixture.content[0].problemIds), ['A', 'C']);
  await page.getByLabel('自动检查间隔', { exact: true }).selectOption('12');
  await page.getByRole('button', { name: '保存更新偏好', exact: true }).click();
  await page.getByText('更新偏好已保存。', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => 'githubRepo' in window.panelsFixture.calls.find(call => call.path === 'hub/configure').body), false, 'ordinary preference saving cannot overwrite repository');
  assert.equal(await page.evaluate(() => window.panelsFixture.calls[0].body.intervalHours), 12);
  await page.getByRole('button', { name: '账号与翻译', exact: true }).click();
  const keyInput = page.getByLabel('翻译服务 API Key', { exact: true });
  await page.waitForFunction(() => !document.querySelector('[aria-label="翻译服务 API Key"]')?.disabled);
  assert.equal(await keyInput.getAttribute('type'), 'password');
  assert.equal(await keyInput.inputValue(), '', 'stored key is never echoed');
  await page.getByLabel('翻译模型', { exact: true }).fill('fixture-model');
  await page.getByRole('button', { name: '保存翻译配置', exact: true }).focus();
  await page.keyboard.press('Enter');
  await page.getByText('翻译配置已保存，首次翻译时验证连接。', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => 'apiKey' in window.panelsFixture.calls.filter(call => call.path === 'translation/settings' && call.body).at(-1).body), false, 'empty password keeps existing provider key');
  await keyInput.fill('fixture-not-a-real-secret');
  await page.getByRole('button', { name: '保存翻译配置', exact: true }).click();
  await page.waitForFunction(() => window.panelsFixture.calls.filter(call => call.path === 'translation/settings' && call.body).at(-1).body.apiKey === 'fixture-not-a-real-secret');
  await page.waitForFunction(() => document.querySelector('[aria-label="翻译服务 API Key"]').value === '');
  await page.getByRole('button', { name: '清除本机密钥', exact: true }).click();
  await page.getByText('已清除本机保存的密钥；已有环境配置仍可能继续生效。', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.panelsFixture.calls.filter(call => call.path === 'translation/settings' && call.body).at(-1).body.apiKey), '', 'clearing requires explicit empty API key');
  await page.getByLabel('翻译服务', { exact: true }).selectOption('huoshan');
  await page.getByLabel('翻译模型', { exact: true }).fill('fixture-endpoint');
  await page.getByRole('button', { name: '保存翻译配置', exact: true }).click();
  await page.getByText('翻译配置已保存，首次翻译时验证连接。', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.panelsFixture.translation.provider), 'huoshan');
  assert.equal(await page.evaluate(() => window.panelsFixture.translation.keyStored), false, 'changing providers never reuses another service key');
  for (const width of [1050, 2048]) {
    await page.setViewportSize({ width, height: 900 });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; document.documentElement.style.fontSize = '18px'; window.panelsFixture.changeView('competition'); });
    await page.locator('.competition-card').first().waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${width}px layout stays within viewport`);
  }
  await page.screenshot({ path: path.join(root, 'tests/screenshots/v4-panels-dark.png'), animations: 'disabled' });
  assert.deepEqual(errors, []);
  console.log('V4 panels: exact notification targets, real-date order, precise difficulty, recommendations, preferences and responsive layout passed.');
} finally { await browser.close(); await server.close(); }
