import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { createServer } from 'vite';
import { mkdir } from 'node:fs/promises';
const vite = await createServer({ server: { host: '127.0.0.1', port: 18769, strictPort: true } });
await vite.listen();
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 2048, height: 1152 } });
page.setDefaultTimeout(10000);
const errors = [], writes = [];
page.on('pageerror', issue => errors.push(issue.message));
const now = () => new Date().toISOString();
const rows = ['A', 'B', 'C', 'D', 'E', 'F'].map((letter, i) => ({ id: '周赛 164::' + letter, contest: '周赛 164', problem: letter, title: ['前缀练习', '简单枚举', '背包练习', '区间统计', '数论练习', '字符串练习'][i], tags: [['前缀和'], ['枚举'], ['背包 DP'], ['差分'], ['素数'], ['KMP']][i], knowledge: ['前缀和', '枚举', '背包 DP', '差分', '素数', 'KMP'][i], platform: '牛客', series: '周赛', difficulty: 1100 + i * 200, contestDate: '2026-09-15T12:00:00Z', url: 'https://ac.nowcoder.com/acm/contest/126120/' + letter, solutionAvailable: true }));
rows.push({ ...rows[0], id: '周赛 123::C', contest: '周赛 123', problem: 'C', title: '旧比赛题', contestDate: '2025-02-01T12:00:00Z', difficulty: 1300 });
const categories = [{ name: '基础技巧', tags: ['前缀和', '枚举'], children: [{ name: '前缀和', tags: ['前缀和'], children: [] }] }];
const workspace = () => ({ training: [], sets: [], contests: [], activeContest: null, summary: { total: 0, accepted: 0, attempts: 0, due: 0, pending: 0 }, now: now() });
const recommendation = { name: '前缀和', reason: '先完成邻近难度的基础题', ids: [rows[0].id], stage: 'foundation', band: { min: 1000, max: 1250, target: 1100 }, problem: rows[0] };
const insights = { summary: {}, growth: { level: 1, currentLevelXp: 0, nextLevelXp: 500, totalXp: 0 }, knowledge: [], recommendations: [recommendation], achievements: [], activity: [], assessment: { rating: null, recommendationLevel: 1100, recommendationBasis: '证据不足，先从基础训练带开始', platforms: [] } };
const notification = { id: 'updated-1', type: 'content', title: '两题新增题解', body: '新增两道已归档题解', createdAt: now(), read: false, count: 2, problemIds: [rows[1].id, rows[6].id], solutionIds: [], problemUrls: [] };
const hub = { version: '0.4.0', settings: { githubRepo: '3097729287/acm-agent-workflow', autoSync: true, intervalHours: 6, minDifficulty: 1000, maxDifficulty: 2199, accounts: { codeforces: '', atcoder: '', nowcoder: '', luogu: '' } }, accounts: [], sync: { busy: false, message: '同步完成', providers: [] }, updates: { configured: true, currentVersion: '0.4.0', repository: '3097729287/acm-agent-workflow' }, notifications: [notification] };
const lesson = { id: 'lecture-1', title: '从零讲：前缀和', concept: '前缀和', tags: ['前缀和'], sourceContest: '周赛 164', sourceProblem: 'A', sourceTitle: rows[0].title, sourceProblemIds: [rows[0].id], available: true, images: {}, markdown: '### 从零讲：前缀和\n\nlecture-proof：用 $s_i-s_{l-1}$ 得到区间和。\n\n```cpp\nint sum = 0;\n```' };
let officialCount = 0, currentSubmission = null;
await page.route('**/api/**', async route => {
  const request = route.request(), url = new URL(request.url()), path = url.pathname, id = url.searchParams.get('id');
  const body = request.method() === 'POST' ? request.postDataJSON() : null;
  if (body) { assert.equal(request.headers()['x-tb-token'], 'fixture'); writes.push({ path, body }); }
  let value;
  if (path === '/api/data') value = { rows, categories, token: 'fixture', statuses: [], today: now().slice(0, 10), revision: 'fixture' };
  else if (path === '/api/workspace') value = workspace();
  else if (path === '/api/inbox') value = { pending: 0, errors: [] };
  else if (path === '/api/hub') value = hub;
  else if (path === '/api/insights') value = insights;
  else if (path === '/api/hub/dismiss') { notification.read = true; value = hub; }
  else if (path === '/api/hub/configure') { Object.assign(hub.settings, body); value = hub; }
  else if (path === '/api/hub/sync') value = hub;
  else if (path === '/api/translation/settings') value = { provider: 'deepseek', providerName: 'DeepSeek', model: 'deepseek-chat', configured: false, verified: false, keyStored: false, keySource: '未配置', providers: [{ id: 'deepseek', name: 'DeepSeek', defaultModel: 'deepseek-chat' }, { id: 'huoshan', name: '火山', defaultModel: 'doubao-seed-code' }], notice: '只发送公开题面' };
  else if (path === '/api/lectures') value = { lectures: [lesson], revision: 'one' };
  else if (path === '/api/lecture') value = lesson;
  else if (path === '/api/solution') value = { title: rows.find(r => r.id === id)?.title, markdown: '## 题意\n\n计算区间和。\n\n' + lesson.markdown + '\n\n### 思路\n\nsolution-proof：把前缀相减。', lectures: [lesson] };
  else if (path === '/api/problem') value = { id, title: rows.find(r => r.id === id)?.title, difficulty: rows.find(r => r.id === id)?.difficulty, markdown: '## Problem Statement\n\nPrint the number $n$.\n\n## Input\nAn integer $n$.', samples: [{ name: '样例 1', input: '1\n', output: '1\n' }], url: rows.find(r => r.id === id)?.url, limits: { timeMs: 2000, memoryMb: 256 }, judge: { scope: 'samples', label: '仅官方样例', cases: 1 }, locked: false, draft: '', submissions: [], statementAvailable: true };
  else if (path === '/api/problem/translate') value = { id: body?.id || id, markdown: '## 题目描述\n\n输出数字 $n$。\n\n## 输入\n一个整数 $n$。', provider: 'fixture', sourceLanguage: 'en', targetLanguage: 'zh-CN', cached: true };
  else if (path === '/api/training/start') value = { workspace: workspace() };
  else if (path === '/api/draft') value = { savedAt: now() };
  else if (path === '/api/official/submit' || path === '/api/official/open') { officialCount++; value = { sessionId: 'official-fixture', platform: '牛客', status: 'needs_login', message: '在同一主窗口中登录原站' }; }
  else if (path === '/api/official/status') value = { sessionId: 'official-fixture', status: 'needs_login', message: '在同一主窗口中登录原站' };
  else if (path === '/api/official/close') value = { status: 'closed' };
  else if (path === '/api/submissions' && body) { currentSubmission = { id: 'sample-1', problemId: body.id, mode: 'run', sampleRun: true, verdict: 'QUEUED', submittedAt: now(), scope: 'samples', code: body.code }; value = { submission: currentSubmission }; }
  else if (path === '/api/submission') { Object.assign(currentSubmission, { verdict: 'WA', finishedAt: now(), passed: 0, total: 1, output: '2\n', message: '样例输出不匹配', caseResults: [{ name: '样例 1', input: '1\n', expected: '1\n', actual: '2\n', verdict: 'WA', timeMs: 2 }] }); value = { submission: currentSubmission, workspace: workspace() }; }
  else if (path === '/api/submissions') value = { submissions: [] };
  else throw new Error('Unhandled v4 API: ' + path);
  await route.fulfill({ json: value });
});
try {
  await page.goto('http://127.0.0.1:18769');
  await page.getByRole('button', { name: '从零讲', exact: true }).waitFor();
  await page.keyboard.press('Control+2');
  assert.equal(await page.locator('.problem-table tbody tr').first().getAttribute('data-id'), rows[0].id, 'new contest first, A-F order preserved');
  assert.equal(await page.locator('.problem-table tbody tr').last().getAttribute('data-id'), rows[6].id, 'old contest last');
  await page.keyboard.press('Control+4');
  assert.ok((await page.locator('.competition-card').first().getAttribute('aria-label')).includes('周赛 164'));
  const tokenColors = await page.locator('.competition-problem-token .competition-difficulty').evaluateAll(nodes => [...new Set(nodes.map(node => getComputedStyle(node).color))]);
  assert.ok(tokenColors.length >= 3, 'ratings have distinct accessible colours');
  await mkdir('tests/screenshots', { recursive: true });
  await page.screenshot({ path: 'tests/screenshots/v4-competitions.png', animations: 'disabled' });
  await page.keyboard.press('Control+5');
  const main = await page.locator('.create-main').boundingBox(), sidebar = await page.locator('.sidebar').boundingBox();
  assert.ok(main.x - sidebar.width < 45, 'no 260px centred gutter');
  await page.getByText(rows[0].title, { exact: true }).waitFor();
  await page.screenshot({ path: 'tests/screenshots/v4-mock.png', animations: 'disabled' });
  await page.keyboard.press('Control+0');
  assert.equal(await page.getByRole('textbox', { name: 'GitHub公开仓库' }).count(), 0, 'known repo has no redundant normal field');
  assert.equal(await page.locator('.settings-column').count(), 2);
  await page.getByRole('button', { name: '字号 18', exact: true }).press('Enter');
  await page.getByRole('button', { name: '更新通知', exact: true }).press('Enter');
  const noticeRow = page.getByRole('dialog').locator('.update-notification').filter({ hasText: notification.title });
  await noticeRow.locator('button.update-notification-main').press('Enter');
  await page.locator('.table-scroll').waitFor();
  assert.equal(await page.locator('.problem-table tbody tr').count(), 2, 'notification only selects exact changed items');
  assert.equal(await page.getByRole('button', { name: '清除更新内容筛选' }).count(), 1);
  await page.getByRole('button', { name: '清除更新内容筛选' }).press('Enter');
  await page.locator('.table-scroll').focus();
  await page.keyboard.press('u');
  await page.locator('.reader-panel').waitFor();
  const disclosure = page.locator('.reader-panel .lecture-disclosure').first();
  assert.equal(await disclosure.getAttribute('open'), null);
  assert.equal(await disclosure.getByText(/lecture-proof/).count(), 0, 'full lecture initially collapsed');
  await disclosure.locator('summary').press('Enter');
  await disclosure.getByText(/lecture-proof/).waitFor();
  await page.keyboard.press('Escape');
  await page.keyboard.press('Control+9');
  await page.getByRole('button', { name: /前缀和.*周赛 164/ }).press('Enter');
  await page.getByRole('article', { name: '知识讲解正文' }).getByText(/lecture-proof/).waitFor();
  await page.screenshot({ path: 'tests/screenshots/v4-lectures.png', animations: 'disabled' });
  await page.keyboard.press('Control+7');
  await page.locator('.progress-recommendations').getByText(rows[0].title, { exact: true }).waitFor();
  await page.locator('.progress-recommendations').getByText('1100', { exact: true }).waitFor();
  await page.screenshot({ path: 'tests/screenshots/v4-growth.png', animations: 'disabled' });
  await page.keyboard.press('Control+2');
  await page.getByRole('button', { name: rows[0].title, exact: true }).press('Enter');
  const editor = page.getByRole('textbox', { name: 'C++ 代码', exact: true });
  await editor.fill('#include <iostream>\nint main(){std::cout << 2;}');
  await editor.press('Control+r');
  await page.getByText(/样例输出不匹配/).waitFor();
  await page.getByText('预期输出', { exact: true }).waitFor();
  await page.getByText('实际输出', { exact: true }).waitFor();
  assert.equal(writes.find(item => item.path === '/api/submissions')?.body.sampleRun, true);
  await page.getByRole('button', { name: /中文|翻译/ }).first().press('Enter');
  await page.getByText('输出数字', { exact: false }).waitFor();
  await editor.focus(); await Promise.all([page.waitForResponse(reply => reply.url().includes('/api/official/submit')), editor.press('Control+Shift+Enter')]);
  assert.equal(officialCount, 1);
  await mkdir('tests/screenshots', { recursive: true });
  await page.screenshot({ path: 'tests/screenshots/v4-workbench.png', animations: 'disabled' });
  for (const width of [2048, 1050]) {
    await page.setViewportSize({ width, height: width === 1050 ? 700 : 1152 });
    await page.keyboard.press('Control+0');
    await page.waitForTimeout(150);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.ok(await page.locator('.settings-page').evaluate(node => node.scrollWidth <= node.clientWidth + 1));
    await page.screenshot({ path: `tests/screenshots/v4-settings-${width}.png`, animations: 'disabled' });
  }
  await page.setViewportSize({ width: 2048, height: 1152 });
  await page.getByRole('button', { name: '云白浅色', exact: true }).press('Enter');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  await page.screenshot({ path: 'tests/screenshots/v4-settings-light-2048.png', animations: 'disabled' });
  await page.keyboard.press('Control+5');
  await page.screenshot({ path: 'tests/screenshots/v4-mock-light-2048.png', animations: 'disabled' });
  assert.ok(await page.locator('.create-main').evaluate(node => node.scrollWidth <= node.clientWidth + 1));
  await page.keyboard.press('Control+4');
  await page.screenshot({ path: 'tests/screenshots/v4-competitions-light-2048.png', animations: 'disabled' });
  assert.deepEqual(errors, []);
  assert.equal(writes.some(item => item.path === '/api/status'), false);
  console.log('v4 UI passed: chronological lists, coloured ratings, compact layouts, exact notification targets, folded/live lectures, level-aware practice, sample diff, Chinese toggle, official client, keyboard and large-font layouts.');
} finally { await browser.close(); await vite.close(); }
