import assert from 'node:assert/strict';
import {matches,organizeCategories,categoryStats} from '../src/models/model.js';
import {briefSolution} from '../src/lib/practiceMetadata.js';
const easy='### 题意\n\n统计总和。\n\n### 思路\n\n累加每个数。\n\n#### 正确性\n\n完整证明保留。\n\n### 参考代码\n\n```cpp\nint main(){}\n// ### not a heading\n```\n\n### 复杂度\n\n线性。';
assert.match(briefSolution(easy,800),/累加每个数/);
assert.match(briefSolution(easy,800),/int main\(\)\{\}\n\/\/ ### not a heading/);
assert.equal(briefSolution(easy,800).includes('完整证明'),false);
assert.equal(briefSolution(easy,2000),null);
assert.equal(briefSolution(easy,null),null);
assert.equal(briefSolution('### 思路\n\n无完整代码',800),null);
const row={contest:'周赛 164',problem:'C',title:'练习',knowledge:'LCA',tags:['LCA'],difficulty:1700,status:'待重写',platform:'牛客'};
assert.equal(matches(row,'周赛 164 C 1700 待重写'),true);
assert.equal(matches(row,'周赛 123'),false);
assert.equal(matches(row,'1600-1800'),true);
assert.equal(matches({...row,difficulty:null},'1600-1800'),false);
assert.equal(matches(row,'E'),false);
const source=[{name:'模拟',tags:['模拟'],children:[]},{name:'线性 DP',tags:['线性 DP','背包 DP'],children:[{name:'背包 DP',tags:['背包 DP'],children:[]}]},{name:'数学',tags:['素数'],children:[{name:'数论',tags:['素数'],children:[]}]},{name:'计数',tags:['组合计数'],children:[]},{name:'新专题',tags:['新专题'],children:[]}];
const grouped=organizeCategories(source);
assert.deepEqual(new Set(grouped.flatMap(n=>n.tags)),new Set(source.flatMap(n=>n.tags)));
assert.equal(grouped.find(n=>n.name==='动态规划').children[0].name,'背包 DP');
assert.equal(grouped.find(n=>n.name==='数学与计数').children.length,2);
assert.equal(grouped.find(n=>n.name==='专题方法').children[0].name,'新专题');
assert.deepEqual(categoryStats({tags:['LCA','图论']},[row,{...row,id:'another',tags:['LCA','图论'],status:'独立AC'}]),{total:2,passed:1,weak:1});
console.log('MODEL OK: compound search, difficulty ranges, lossless category grouping, unique problem counts');
